"""empty message

Revision ID: 6f7b6b4ef131
Revises: 243da6e75e4f
Create Date: 2021-04-30 22:30:17.024176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7b6b4ef131'
down_revision = '243da6e75e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorial', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorial', 'name')
    # ### end Alembic commands ###
