"""empty message

Revision ID: adfc69958784
Revises: fc79490d9e7a
Create Date: 2021-04-23 01:25:13.724499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfc69958784'
down_revision = 'fc79490d9e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
